Repository AlexReusC/colpos_alfa, pull requests merged in 2021-03, with the labels that each got.

#12 Categoryscreen
  src/app/foros/foro-categorias/foro-categorias.component.css
  src/app/foros/foro-categorias/foro-categorias.component.html
Labels: design

#11 Added simple design #8
  src/app/foros/foro-post-nuevo/foro-post-nuevo.component.css
  src/app/foros/foro-post-nuevo/foro-post-nuevo.component.html
Labels: PR

#14 Single post screen
  angular.json
  src/app/foros/foro-post-nuevo/foro-post-nuevo.component.css
  src/app/foros/foro-post-nuevo/foro-post-nuevo.component.html
Labels: PR, design

#16 Sketch home foros #6
  src/app/foros/foro-home/foro-home.component.css
  src/app/foros/foro-home/foro-home.component.html
Labels: PR
